-- Extensión del laboratorio NL2IR publicado: no altera su catálogo ni la vista.
-- Ejecutar con el mismo esquema de parsing, después de nl2ir-a-que-jugamos/database/install.sql.
set define off
set serveroutput on
whenever sqlerror exit sql.sqlcode

declare
    l_count number;
begin
    select count(*) into l_count from user_tables where table_name = 'NL2IR_GAMES';
    if l_count = 0 then
        raise_application_error(-20010, 'Instala primero el laboratorio NL2IR.');
    end if;
    select count(*) into l_count from user_views where view_name = 'NL2IR_V_LIBRARY';
    if l_count = 0 then
        raise_application_error(-20011, 'Falta la vista NL2IR_V_LIBRARY.');
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'NL2IR_GAME_NIGHTS';

    if l_count = 0 then
        execute immediate q'[
            create table nl2ir_game_nights (
                night_id     number generated by default on null as identity not null,
                title        varchar2(100 char) not null,
                planned_for  date,
                owner_user   varchar2(255 char) not null,
                status_code  varchar2(20 char) default 'DRAFT' not null,
                created_at   timestamp default systimestamp not null,
                constraint nl2ir_game_nights_pk primary key (night_id),
                constraint nl2ir_game_nights_status_ck
                    check (status_code in ('DRAFT', 'CONFIRMED', 'CANCELLED'))
            )
        ]';
    end if;
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'NL2IR_GAME_NIGHT_OPTIONS';

    if l_count = 0 then
        execute immediate q'[
            create table nl2ir_game_night_options (
                night_id  number not null,
                game_id   number(4) not null,
                added_by  varchar2(255 char) not null,
                added_at  timestamp default systimestamp not null,
                constraint nl2ir_game_night_options_pk primary key (night_id, game_id),
                constraint nl2ir_options_night_fk foreign key (night_id)
                    references nl2ir_game_nights (night_id),
                constraint nl2ir_options_game_fk foreign key (game_id)
                    references nl2ir_games (game_id)
            )
        ]';
    end if;
end;
/

create or replace package nl2ir_game_night_api as
    function ensure_draft (
        p_owner_user in varchar2
    ) return number;

    procedure add_options (
        p_night_id   in number,
        p_owner_user in varchar2,
        p_game_ids   in varchar2
    );
end nl2ir_game_night_api;
/

create or replace package body nl2ir_game_night_api as
    function ensure_draft (
        p_owner_user in varchar2
    ) return number is
        l_night_id nl2ir_game_nights.night_id%type;
    begin
        select night_id
          into l_night_id
          from (
              select night_id
                from nl2ir_game_nights
               where owner_user = p_owner_user
                 and status_code = 'DRAFT'
               order by created_at desc
          )
         where rownum = 1;

        return l_night_id;
    exception
        when no_data_found then
            insert into nl2ir_game_nights (title, planned_for, owner_user)
            values ('Propuesta de partida', trunc(sysdate) + 7, p_owner_user)
            returning night_id into l_night_id;
            return l_night_id;
    end ensure_draft;

    procedure add_options (
        p_night_id   in number,
        p_owner_user in varchar2,
        p_game_ids   in varchar2
    ) is
        l_owned_draft_count number;
        l_requested_count   number;
        l_valid_count       number;
        l_invalid_count     number;
    begin
        if p_game_ids is null then
            raise_application_error(-20001, 'Selecciona al menos un juego.');
        end if;

        select count(*)
          into l_owned_draft_count
          from nl2ir_game_nights
         where night_id = p_night_id
           and owner_user = p_owner_user
           and status_code = 'DRAFT';

        if l_owned_draft_count <> 1 then
            raise_application_error(-20002, 'La propuesta no está disponible para el usuario actual.');
        end if;

        select count(*)
          into l_invalid_count
          from table(apex_string.split(p_game_ids, ':')) t
         where not regexp_like(trim(t.column_value), '^[0-9]+$');

        if l_invalid_count > 0 then
            raise_application_error(-20003, 'La selección contiene un identificador no válido.');
        end if;

        select count(*)
          into l_requested_count
          from (
              select distinct to_number(trim(column_value)) as game_id
                from table(apex_string.split(p_game_ids, ':'))
          );

        select count(*)
          into l_valid_count
          from nl2ir_games g
         where g.active_yn = 'Y'
           and g.game_id in (
               select distinct to_number(trim(column_value))
                 from table(apex_string.split(p_game_ids, ':'))
           );

        if l_requested_count = 0 or l_requested_count <> l_valid_count then
            raise_application_error(-20004, 'La selección contiene un juego inexistente o no disponible.');
        end if;

        merge into nl2ir_game_night_options o
        using (
            select p_night_id as night_id,
                   to_number(trim(column_value)) as game_id
              from table(apex_string.split(p_game_ids, ':'))
             group by to_number(trim(column_value))
        ) s
        on (o.night_id = s.night_id and o.game_id = s.game_id)
        when not matched then
            insert (night_id, game_id, added_by)
            values (s.night_id, s.game_id, p_owner_user);
    end add_options;
end nl2ir_game_night_api;
/

prompt Extensión de selección instalada.
