create table ald_customers (
    customer_id       number generated by default as identity
                      primary key,
    customer_name     varchar2(200 char) not null,
    contact_channel   varchar2(20 char) not null
                      constraint ald_customers_channel_ck
                      check (contact_channel in ('EMAIL', 'PHONE')),
    email             varchar2(320 char)
);

insert into ald_customers (customer_name, contact_channel, email)
values ('Customer 1', 'EMAIL', null);

insert into ald_customers (customer_name, contact_channel, email)
values ('Customer 2', 'PHONE', null);

commit;
